name: helseveileder
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython
  - ipykernel
  - ipywidgets
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - scipy
  - statsmodels
  - nltk
  - wordcloud



## Configure the Conda-environment helseveileder for data analysis, computational imaging and modeling (only once):
# conda env create -f environment.yml

## To make a HELSEVEILEDER kernel (optional):
# python -m ipykernel install --user --name helseveileder --display-name "HELSEVEILEDER"

## To activate the helseveileder conda environment:
# conda activate helseveileder

## To update the helseveileder conda environment:
# conda env update -f environment.yml

## To remove and reinstall the helseveileder environment (if installation problems):
# conda deactivate
# conda env remove -n helseveileder
# conda env create -f environment.yml
